# Theme Settings
minimal_mistakes_skin    : "mint" # try "dark" or "sunrise" if you prefer different vibes

# Site Settings
locale                   : "en-US"
title                    : "Salma Zaime"
title_separator          : "-"
subtitle                 : "Cloud | Blue Team | AI "
name                     : "Salma Zaime"
description              : "Cybersecurity student building hands-on projects in cloud security, blue team detection engineering, and AI for security."
url                      : "https://github.com/salmazaime/portfolio/blob/main/_config.yml" 
baseurl                  : "/portfolio" # since you're using a repo named portfolio
repository               : "salmazaime/portfolio"
logo                     : # optional, add later if you upload a logo to /assets/images/
masthead_title           : " " # keep masthead clean

breadcrumbs              : true
words_per_minute         : 200
enable_copy_code_button  : true
copyright                : "© 2025 Salma Zaime"

# Social Sharing
twitter:
  username               : 
facebook:
  username               : 
og_image                 : # add a preview image later
social:
  type                   : Person
  name                   : "Salma Zaime"
  links:
    - "https://github.com/salmazaime"
    - "https://www.linkedin.com/in/salmazaime" # replace with your LinkedIn URL

# Site Author
author:
  name             : "Salma Zaime"
  avatar           : "/assets/images/avatar.png" # put a profile image later
  bio              : "Cybersecurity student passionate about cloud security, detection engineering, and AI. Documenting hands-on projects and learning in public."
  location         : "France"
  email            : "your.email@example.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your.email@example.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/salmazaime"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/salmazaime"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/salmazaime"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/salmazaime"
  since: "2025"

# Reading Files
include:
  - .htaccess
  - _pages

# Outputting
permalink: /:categories/:title/
timezone: Europe/Paris

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
